#!/usr/bin/php
<?php
//require_once('../include_admin/auth.inc.php');
require_once('../include_admin/const.inc.php');
require_once('../include_admin/db.inc.php');
require_once('../include_admin/function.inc.php');
GenerateStreamFM();
GeneratePOPRNB();
GenerateRAP();
GenerateELECTRONIC();
GenerateROCK();
GeneratePlaylists();
?>
