<?php
define('MEDIA_PATH','/var/www/radio.stream.uz/media/');
define('RADIO_DB_HOST','localhost');
define('RADIO_DB_NAME','radiostream');
define('RADIO_DB_USER','radiostream');
define('RADIO_DB_PASSWORD','nee7ziCiej');
define('MUSIC_DB_HOST','localhost');
define('MUSIC_DB_NAME','music_stream_uz');
define('MUSIC_DB_USER','musicstream');
define('MUSIC_DB_PASSWORD','nosarkormp3');
?>
